import React from "react";
import ProjectCard from "../components/ProjectCard";

const projects = [
  {
    title: "ResuMatrix: AI-Powered Resume Analyzer & Ranker",
    description: "● Developed an end-to-end ML pipeline for resume filtering and ranking, automating candidate evaluation based on job descriptions. Built a XGBoost model to train on embeddings generated by SBERT and Pinecone to produce similarity scores for resume classification (fit/no fit). ● Fine-tuned LLMs (Gemini, Mistral 7, Borda) for ranking and optimizing candidate selection process which improved precision by 25-30% on job description-resume relevance. Data Pipelines for both models were orchestrated via Apache Airflow. ● Integrated CI/CD automation using Jenkins and Docker, for continuous model updates (reducing manual effort by 60% and processing 400+ resumes in minutes). Deployment on Google Cloud Platform (GCP) helped cut cloud storage costs by 40%, optimizing resource usage. ● Tracked model performance using MLflow (ensuring 100% reproducibility). Designed automated retraining to address concept drift and maintain model accuracy. Deployed an interactive dashboard (Grafana/Streamlit) for real-time insights and recruiter-friendly visualization.",
    date: "Jan 2025 - May 2025",
    githubLink: "https://github.com/NishchithRao-hub/ResuMatrix"
  },
  {
    title: "Weather-Driven Smart Home Energy Consumption and its Optimization",
    description: "● Performed time series analysis and developed an ML pipeline to forecast and optimize smart home energy consumption using VAR (Vector Autoregression), Prophet, and LightGBM Regressor models, leveraging appliance-level usage data and weather conditions. ● Designed a regression-based optimization strategy to minimize high demand usage by simulating appliances schedule and reducing peak consumption patterns. This resulted in a reduction of traditional energy consumption costs by 15%.",
    date: "Oct 2024 - Dec 2024",
    githubLink: "https://github.com/NishchithRao-hub/Weather-Driven-Smart-Home-Energy-Consumption-And-Its-Optimization"
  },
  {
    title: "Mars Terrain Exploration and Navigation Framework",
    description: "● Engineered an autonomous robotic exploration system for simulated Martian terrains using Deep Reinforcement Learning (DRL) algorithms - Proximal Policy Optimization (PPO) and Twin Delayed DDPG (TD3), integrated with OpenAI Gym, PyTorch, and NumPy. ● Designed custom reward functions to enhance terrain coverage, energy efficiency, and obstacle avoidance; simulated dynamics with Matplotlib, OpenCV, and Unity ML-Agents for realistic visualization and agent feedback.",
    date: "Sep 2024 - Nov 2024",
    githubLink: "https://github.com/NishchithRao-hub/Autonomous-Mars-Terrain-Exploration-and-Navigation-Framework"
  },
  {
    title: "Fitness Tracker Application",
    description: "● Developed a full stack application with Java and Chart.js, aimed at tracking/visualizing calories, fitness goals and add/manage diets for users. ● Created 14 REST API endpoints using FastAPI and Swagger, designed frontend with AngularJS, styled with Tailwind CSS and JavaScript for website design. Integrated Firebase Authentication for secure user login and session management. ● Achieved 90%+ code coverage by writing effective tests using PyTest, in addition to JUnit testing/Mockito, proving its usefulness in smart watches. Used Redis for caching frequently accessed data. Won 2nd place for this application in the Annual Capgemini Hack Week, 2022.",
    date: "Feb 2022 - June 2022",
    githubLink: "https://github.com/NishchithRao-hub/Fitness-Tracker-"
  }
  // Add more projects here as needed
];

const Projects = () => {
  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8 text-center text-gray-800 dark:text-white">Projects</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {projects.map((project, idx) => (
          <ProjectCard key={idx} {...project} />
        ))}
      </div>
    </div>
  );
};

export default Projects;